### ISSUE TITLE
**UPDATE LOCAL REPOSITORY**

### ISSUE THREAD

**Issue by Jesse-Dekker** [course-dprep/team-project-dprep_group3#27]
> **SUMMARY** Directory structure created, however, empty directories not visible. For now only src/data-preparation is present. Please update your local repository and add files to their respective directories from now on.  

 _Originally posted by @Jesse-Dekker in [#10](https://github.com/course-dprep/team-project-dprep_group3/issues/10#issuecomment-1991297258)_

**Comment by Jennicka23** [comment]
Mine is also up-to-date!

**Comment by BusenazAtahan** [comment]
Mine local repository is also up-to-date!

**Comment by silabozoglu** [comment]
My local repository is also up-to-date!
